//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2012-12-05 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Thu 30-Oct-2008 14:59:38)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class Mensagem extends Segmento {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=objOrigem KEEP=NO
  public volatile Objeto objOrigem = null;
// ***** VDMTOOLS END Name=objOrigem

// ***** VDMTOOLS START Name=objDestino KEEP=NO
  public volatile Objeto objDestino = null;
// ***** VDMTOOLS END Name=objDestino

// ***** VDMTOOLS START Name=tipo KEEP=NO
  public volatile String tipo = null;
// ***** VDMTOOLS END Name=tipo


// ***** VDMTOOLS START Name=MensagemSentinel KEEP=NO
  class MensagemSentinel extends SegmentoSentinel {

    public final int Mensagem = 4;

    public final int getSequencias = 5;

    public final int nr_functions = 6;


    public MensagemSentinel () throws CGException {}


    public MensagemSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=MensagemSentinel
;

// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new MensagemSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Mensagem KEEP=NO
  private void vdm_init_Mensagem () throws CGException {
    try {
      tipo = new String("message");
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Mensagem


// ***** VDMTOOLS START Name=Mensagem KEEP=NO
  public Mensagem () throws CGException {
    vdm_init_Mensagem();
  }
// ***** VDMTOOLS END Name=Mensagem


// ***** VDMTOOLS START Name=Mensagem#5|String|Integer|String|Objeto|Objeto KEEP=NO
  public Mensagem (final String n, final Integer i, final String t, final Objeto objO, final Objeto objD) throws CGException {

    if (!this.pre_Mensagem(n, i, t, objO, objD).booleanValue()) 
      UTIL.RunTime("Run-Time Error:Precondition failure in Mensagem");
    vdm_init_Mensagem();
    {

      nome = UTIL.ConvertToString(UTIL.clone(n));
      id = UTIL.NumberToInt(UTIL.clone(i));
      tipo = UTIL.ConvertToString(UTIL.clone(t));
      objOrigem = (Objeto) UTIL.clone(objO);
      objDestino = (Objeto) UTIL.clone(objD);
      HashSet rhs_11 = new HashSet();
      Integer enum_set_12 = null;
      enum_set_12 = objOrigem.id;
      rhs_11 = new HashSet();
      rhs_11.add(enum_set_12);
      Integer enum_set_14 = null;
      enum_set_14 = objDestino.id;
      rhs_11.add(enum_set_14);
      ids = (HashSet) UTIL.clone(rhs_11);
    }
  }
// ***** VDMTOOLS END Name=Mensagem#5|String|Integer|String|Objeto|Objeto


// ***** VDMTOOLS START Name=pre_Mensagem#5|String|Integer|String|Objeto|Objeto KEEP=NO
  public Boolean pre_Mensagem (final String n, final Integer i, final String t, final Objeto objO, final Objeto objD) throws CGException {

    Boolean varRes_6 = null;
    {
      if ((varRes_6 = new Boolean((new Integer(n.length()).intValue()) > (new Integer(0).intValue()))).booleanValue()) {

        Boolean var2_11 = null;
        HashSet var2_13 = new HashSet();
        var2_13 = new HashSet();
        var2_13.add(new String("message"));
        var2_13.add(new String("action"));
        var2_13.add(new String("asynchronous"));
        var2_13.add(new String("link"));
        var2_13.add(new String("destroy"));
        var2_13.add(new String("call"));
        var2_13.add(new String("create"));
        var2_13.add(new String("other"));
        var2_11 = new Boolean(var2_13.contains(t));
        varRes_6 = var2_11;
      }
    }
    return varRes_6;
  }
// ***** VDMTOOLS END Name=pre_Mensagem#5|String|Integer|String|Objeto|Objeto


// ***** VDMTOOLS START Name=getSequencias KEEP=NO
  public Vector getSequencias () throws CGException {

    sentinel.entering(((MensagemSentinel) sentinel).getSequencias);
    try {

      Vector rexpr_1 = null;
      Vector e_seq_2 = null;
      e_seq_2 = new Vector();
      e_seq_2.add(this);
      rexpr_1 = new Vector();
      rexpr_1.add(e_seq_2);
      return rexpr_1;
    }
    finally {
      sentinel.leaving(((MensagemSentinel) sentinel).getSequencias);
    }
  }
// ***** VDMTOOLS END Name=getSequencias

}
;
