//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2012-12-05 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Thu 30-Oct-2008 14:59:38)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class Objeto implements EvaluatePP {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=nome KEEP=NO
  public volatile String nome = null;
// ***** VDMTOOLS END Name=nome

// ***** VDMTOOLS START Name=tipo KEEP=NO
  public volatile String tipo = null;
// ***** VDMTOOLS END Name=tipo

// ***** VDMTOOLS START Name=id KEEP=NO
  public volatile Integer id = null;
// ***** VDMTOOLS END Name=id

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=ObjetoSentinel KEEP=NO
  class ObjetoSentinel extends Sentinel {

    public final int Objeto = 0;

    public final int nr_functions = 1;


    public ObjetoSentinel () throws CGException {}


    public ObjetoSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=ObjetoSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return new Boolean(true);
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new ObjetoSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Objeto KEEP=NO
  private void vdm_init_Objeto () throws CGException {
    try {

      setSentinel();
      nome = UTIL.ConvertToString(new String());
      tipo = new String("Object");
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Objeto


// ***** VDMTOOLS START Name=Objeto KEEP=NO
  public Objeto () throws CGException {
    vdm_init_Objeto();
  }
// ***** VDMTOOLS END Name=Objeto


// ***** VDMTOOLS START Name=Objeto#3|String|Integer|String KEEP=NO
  public Objeto (final String n, final Integer i, final String t) throws CGException {

    if (!this.pre_Objeto(n, i, t).booleanValue()) 
      UTIL.RunTime("Run-Time Error:Precondition failure in Objeto");
    vdm_init_Objeto();
    {

      nome = UTIL.ConvertToString(UTIL.clone(n));
      id = UTIL.NumberToInt(UTIL.clone(i));
      tipo = UTIL.ConvertToString(UTIL.clone(t));
    }
  }
// ***** VDMTOOLS END Name=Objeto#3|String|Integer|String


// ***** VDMTOOLS START Name=pre_Objeto#3|String|Integer|String KEEP=NO
  public Boolean pre_Objeto (final String n, final Integer i, final String t) throws CGException {

    Boolean varRes_4 = null;
    {
      if ((varRes_4 = new Boolean((new Integer(n.length()).intValue()) > (new Integer(0).intValue()))).booleanValue()) {

        Boolean var2_9 = null;
        HashSet var2_11 = new HashSet();
        var2_11 = new HashSet();
        var2_11.add(new String("Actor"));
        var2_11.add(new String("Unit"));
        var2_11.add(new String("Object"));
        var2_11.add(new String("Other"));
        var2_9 = new Boolean(var2_11.contains(t));
        varRes_4 = var2_9;
      }
    }
    return varRes_4;
  }
// ***** VDMTOOLS END Name=pre_Objeto#3|String|Integer|String

}
;
